[build]
builder = "nixpacks"

[deploy]
startCommand = "bundle exec rails server -b 0.0.0.0 -e production"
healthCheckPath = "/up"
healthCheckTimeout = 300
restartPolicyType = "always"

[deploy.releaseCommand]
command = "bundle exec rails db:create db:migrate db:seed"