[build]
builder = "nixpacks"

[deploy]
startCommand = "bundle exec puma -C config/puma.rb"
restartPolicyType = "on_failure"

# Run migration when deploying
[deploy.releaseCommand]
command = "bundle exec rails db:migrate"