[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "always"
startCommand = "bundle exec rails server -b 0.0.0.0 -e production"
healthCheckPath = "/up"
healthCheckTimeout = 300

[deploy.releaseCommand]
command = "bundle exec rails db:migrate"