[build]
builder = "nixpacks"

[deploy]
startCommand = "bin/rails db:create db:migrate db:seed && bundle exec rails server -b 0.0.0.0 -e production"
healthCheckPath = "/up"
healthCheckTimeout = 300
restartPolicyType = "always"